# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/centos7"
  config.vm.hostname = "develop"
  config.vm.base_mac = "005056312011"
  config.vm.base_address = "192.168.10.11"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "vmware_desktop" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # 关闭防火墙
    systemctl stop firewalld
    systemctl disable firewalld

    # 关闭selinux
    sed -i 's/enforcing/permissive/' /etc/selinux/config
    setenforce 0

    # 关闭swap
    swapoff -a
    sed -ri 's/.*swap.*/#&/' /etc/fstab

  SHELL
end
