# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  (1..3).each do |i|

    config.vm.define "node#{i}" do |node|
      node.vm.box = "generic/centos7"
      node.vm.hostname = "node#{i}"
      node.vm.network "public_network", ip: "192.168.1.2#{i}", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"
      node.vm.synced_folder ".", "/vagrant"

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false      
        vb.memory = "4096"
        vb.cpus = "4"
      end

      node.vm.provision "shell", inline: <<-SHELL
        # 关闭防火墙
        systemctl stop firewalld
        systemctl disable firewalld

        # 关闭selinux
        sed -i 's/enforcing/permissive/' /etc/selinux/config
        setenforce 0

        # 关闭swap
        swapoff -a
        sed -ri 's/.*swap.*/#&/' /etc/fstab
      SHELL

    end

  end

end
